### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by PrincessGod** [greggman/webgl-fundamentals#86]
Hi @greggman , I am working on translate a simplify-chinese version, and comes a problem when I run `npm run build`, there are some error messages and log info, hope you can help me fix it. These tutorials really excellent and I hope I can do something to help more people can read it.
Actually I found it not interrupt the job. I can use http-server scan my translated pages. So it that means I can translate and preview at local and just pull request my "zh-cn" folder ? Thanks!

NPM Errors
![powershell_2017-07-14_00-37-16](https://user-images.githubusercontent.com/20556748/28177933-32d8d710-682f-11e7-896e-31be54af1113.png)

Log Info
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\soft\\Nodejs\\node.exe',
1 verbose cli   'D:\\soft\\Nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle webgl-fundamentals@0.0.0~prebuild: webgl-fundamentals@0.0.0
6 silly lifecycle webgl-fundamentals@0.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle webgl-fundamentals@0.0.0~build: webgl-fundamentals@0.0.0
8 verbose lifecycle webgl-fundamentals@0.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle webgl-fundamentals@0.0.0~build: PATH: D:\soft\Nodejs\node_modules\npm\bin\node-gyp-bin;E:\webgl-fundamentals-master\webgl-fundamentals-master\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\soft\Git\cmd;C:\ProgramData\chocolatey\bin;D:\soft\Sublime Text 3;D:\soft\Nodejs\;C:\Users\PrincessGod\AppData\Local\Microsoft\WindowsApps;C:\Users\PrincessGod\AppData\Roaming\npm
10 verbose lifecycle webgl-fundamentals@0.0.0~build: CWD: E:\webgl-fundamentals-master\webgl-fundamentals-master
11 silly lifecycle webgl-fundamentals@0.0.0~build: Args: [ '/d /s /c', 'grunt' ]
12 silly lifecycle webgl-fundamentals@0.0.0~build: Returned: code: 3  signal: null
13 info lifecycle webgl-fundamentals@0.0.0~build: Failed to exec build script
14 verbose stack Error: webgl-fundamentals@0.0.0 build: `grunt`
14 verbose stack Exit status 3
14 verbose stack     at EventEmitter.<anonymous> (D:\soft\Nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\soft\Nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid webgl-fundamentals@0.0.0
16 verbose cwd E:\webgl-fundamentals-master\webgl-fundamentals-master
17 verbose Windows_NT 10.0.15063
18 verbose argv "D:\\soft\\Nodejs\\node.exe" "D:\\soft\\Nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 verbose node v8.1.3
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 3
23 error webgl-fundamentals@0.0.0 build: `grunt`
23 error Exit status 3
24 error Failed at the webgl-fundamentals@0.0.0 build script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 3, true ]
```

**Comment by greggman** [comment]
Apparently that's a permissions issue?

https://stackoverflow.com/questions/30744964/what-does-the-elifecycle-node-js-error-mean

https://stackoverflow.com/questions/30239752/npm-start-fails-because-of-node-api-elifecycle

https://stackoverflow.com/questions/42308879/npm-err-code-elifecycle

**Comment by PrincessGod** [comment]
Permissions is fine, I tried last night. and I found it works fine on my laptop today, maybe it's nodejs's version problem, cause my laptop is v6 and PC is V8. I will change the PC version to fix that. and also finish the translation as soon as possible. Good luck !

**Comment by diska** [comment]
I've experienced some build error(different one, maybe).
```
$ npm run build
...
ERROR!:
TypeError: Cannot read property 'dateModified' of undefined
  at C:\Users\KimI\github\webgl-fundamentals\build\js\build.js:385:36
...
```
That error causes 404 error in "https://webglfundamentals.org/webgl/lessons/zh_cn/index.html".

Adding one more file (other than "langinfo.hanson", "index.md", "toc.html") to the directory "/webgl/lessons/zh_cn/" may fix that.

ご参考まで。

**Comment by PrincessGod** [comment]
@diska , thank you. I have change my nodejs to v6, and it's fine now!
